### ISSUE TITLE
Left align hero columns text

### ISSUE THREAD

**Issue by nchevobbe** [tc39/tc39.github.io#114]
Hell there, the website looks great IMO.
I think the readability of the text in the 3 columns would be a bit better left aligned, and with a tad larger padding: 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/578107/53949988-765f3300-40cb-11e9-8acc-3a30e48a4fd6.png">

Here are the changes made:
```css
/* style.css | https://tc39.github.io/beta/assets/css/style.css?v=b97ac5f8ca15096781e40c39dd5bf090b3a13e20 */
@media (min-width: 920px) {
  /* .main-content .intro { */
  .main-content .intro h2 {
    /* text-align: center; */
  }
}

.intro [class*="g-col-"] {
  /* padding: 0 20px; */
  padding: 0 25px;
}
```
