### ISSUE TITLE
Put "Specify Js" title next to logo?

### ISSUE THREAD

**Issue by nchevobbe** [tc39/tc39.github.io#115]
it may re-enforce the branding and purpose of TC39, not sure though

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/578107/53949903-516ac000-40cb-11e9-9f62-d010e60dfedb.png">

Here are the changes made: 
```css
.page-header {
  /* align-items: flex-start; */
  align-items: center;
}

@media (min-width: 920px) {
  .page-title {
    /* line-height: 81px; */
    /* text-align: end; */
  }
}

.page-title {
  /* font-size: 36px; */
  /* line-height: 54px; */
  /* margin: 50px 0 0; */
  margin: 0;
  margin-inline-start: 20px;
  padding: 0;
}

.page-menu {
  /* margin-top: 73.6px; */
}
```
